
mau_binh_siteA:
  profiles:
    1:
      window_title_keyword: "GO88B.CX Thiên Đường Game bài Đổi Thưởng Lớn Nhất Việt Nam"
    2:
      window_title_keyword: "GO88 - P2"
    3:
      window_title_keyword: "GO88 - P3"
